const DIGEST_DATA = {
  stats: {
    processed: 23,
    actionNeeded: 2,
    savedMinutes: 87,
  },
  mustAct: [
    {
      id: 'd1',
      text: 'Approve Atlas API auth flow — Priya waiting, sprint blocked',
      source: 'Gmail + Slack + Notion — linked automatically',
    },
    {
      id: 'd2',
      text: 'Send retention slide to CEO for Q2 deck by EOD',
      source: 'Gmail — data found in Notion Q2 Analytics doc',
    },
  ],
  radar: [
    {
      id: 'd3',
      text: 'Sprint #18 has 3 unresolved Slack blockers — no owner assigned',
      source: 'Slack — flagged by Ankit, Apr 30',
    },
    {
      id: 'd4',
      text: 'Design review for onboarding flow rescheduled — new slot not confirmed',
      source: 'Gmail — Rohan, May 1',
    },
  ],
  fyi: [
    {
      id: 'd5',
      text: 'Build #412 passed, staging deploy complete',
      source: 'GitHub CI — auto-archived',
    },
    {
      id: 'd6',
      text: 'Monthly infra cost report — within budget',
      source: 'Gmail — finance team',
    },
  ],
}

function StatCard({ value, label }) {
  return (
    <div className="bg-gray-50 dark:bg-gray-800 rounded-xl p-4 text-center">
      <div className="text-2xl font-semibold text-gray-800 dark:text-gray-100">
        {value}
      </div>
      <div className="text-xs text-gray-400 mt-1">{label}</div>
    </div>
  )
}

function DigestSection({ title, items, dotColor }) {
  return (
    <div className="mb-6">
      <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-3">
        {title}
      </p>
      <div className="flex flex-col">
        {items.map((item, i) => (
          <div
            key={item.id}
            className={`flex items-start gap-3 py-3 ${
              i < items.length - 1
                ? 'border-b border-gray-100 dark:border-gray-800'
                : ''
            }`}
          >
            <div className={`w-2 h-2 rounded-full flex-shrink-0 mt-1.5 ${dotColor}`} />
            <div>
              <p className="text-sm text-gray-700 dark:text-gray-200 leading-relaxed">
                {item.text}
              </p>
              <p className="text-xs text-gray-400 mt-0.5">{item.source}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export default function DigestPanel() {
  const { stats, mustAct, radar, fyi } = DIGEST_DATA

  return (
    <div>
      {/* Stats */}
      <div className="grid grid-cols-3 gap-3 mb-6">
        <StatCard value={stats.processed} label="Inputs processed" />
        <StatCard value={stats.actionNeeded} label="Need your action" />
        <StatCard value={`${stats.savedMinutes}m`} label="Saved today" />
      </div>

      {/* Sections */}
      <DigestSection
        title="Must act today"
        items={mustAct}
        dotColor="bg-red-400"
      />
      <DigestSection
        title="On your radar"
        items={radar}
        dotColor="bg-amber-400"
      />
      <DigestSection
        title="FYI — no action"
        items={fyi}
        dotColor="bg-emerald-400"
      />

      {/* Footer */}
      <div className="mt-4 flex items-center justify-center gap-1.5">
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
          <circle cx="6" cy="6" r="5" stroke="#6366f1" strokeWidth="1"/>
          <path d="M4 6l1.5 1.5L8 4" stroke="#6366f1" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round"/>
        </svg>
        <span className="text-xs text-indigo-400 font-medium">
          Generated by Nexus Brain · updated 2 min ago
        </span>
      </div>
    </div>
  )
}